CREATE TABLE tweet (
  id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  author VARCHAR(64) NOT NULL,
  content VARCHAR(256) NOT NULL,
  timestamp DATETIME NOT NULL,
  PRIMARY KEY (id)
) ENGINE = InnoDB;
